name: my_kakeibo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  provider: ^6.1.2
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.0
  google_fonts: ^6.2.1
  fl_chart: ^0.69.2
  timezone: ^0.10.0
  realm: ^3.4.1
  uuid: ^4.5.1
  firebase_app_check: ^0.3.1+6
  keyboard_dismisser: ^3.0.0
  result_dart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/launcher/
