name: my_kakeibo
description: "Your personal finance app."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.3.5+11

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  provider: ^6.1.2
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.0
  google_fonts: ^6.2.1
  fl_chart: ^0.69.2
  timezone: ^0.10.0
  uuid: ^4.5.1
  firebase_app_check: ^0.3.1+6
  keyboard_dismisser: ^3.0.0
  result_dart: ^2.0.0
  sqflite: ^2.4.0
  path: ^1.9.0
  firebase_analytics: ^11.4.3
  firebase_crashlytics: ^4.3.3
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.1
  sqflite_common_ffi: ^2.3.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/launcher/
flutter_intl:
  enabled: true
