// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYEQpIFnVouq2ENuLjnGp1tQYJPK1nT2c',
    appId: '1:713195547362:web:05e4fb6a112b80b2cc0cbb',
    messagingSenderId: '713195547362',
    projectId: 'my-kakeibo-f8ca5',
    authDomain: 'my-kakeibo-f8ca5.firebaseapp.com',
    storageBucket: 'my-kakeibo-f8ca5.firebasestorage.app',
    measurementId: 'G-MG6B7SGG4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Sr94lNgxifA4y_8gTtbl5FxTW3vT0Hg',
    appId: '1:713195547362:android:da3e38ab3b452e2ccc0cbb',
    messagingSenderId: '713195547362',
    projectId: 'my-kakeibo-f8ca5',
    storageBucket: 'my-kakeibo-f8ca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBRQFxWOmc27PljrE3tIEaRNvSKd5NYo',
    appId: '1:713195547362:ios:571a9596af80c75acc0cbb',
    messagingSenderId: '713195547362',
    projectId: 'my-kakeibo-f8ca5',
    storageBucket: 'my-kakeibo-f8ca5.firebasestorage.app',
    iosClientId:
        '713195547362-r5r8a6bb5jq4t9pfb519qnup0cdvvtro.apps.googleusercontent.com',
    iosBundleId: 'com.example.myKakeibo',
  );
}
