name: App Distribution

on:
  push:
    tags:
      - v*

jobs:
  build_ipa:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa/Runner.ipa

  build_apk:
    name: Build Flutter APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.24.0
      - run: flutter pub get
      - run: flutter clean
      - name: Decode keystore
        run: echo ${{ secrets.KEYSTORE_BASE64 }} | base64 --decode > android/app/upload-keystore.jks
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties
      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk

  upload_android_to_firebase:
    name: Upload Android to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: build_apk
    steps:
      - uses: actions/checkout@v3

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:411416223259:android:51d56a5cadcc99024fe2be \
            --token ${{ secrets.FIREBASE_AUTH_TOKEN }} \
            --groups "vip"

  upload_ios_to_firebase:
    name: Upload iOS to Firebase App Distribution
    runs-on: macos-latest
    needs: build_ipa
    steps:
      - uses: actions/checkout@v3

      - name: Download IPA
        uses: actions/download-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/ios/ipa/Runner.ipa \
            --app 1:411416223259:ios:5d7f98d7d8674cfb4fe2be \
            --token ${{ secrets.FIREBASE_AUTH_TOKEN }} \
            --groups "vip"